/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tasktwo;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.File;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        String fileName = "app/src/main/resources/data.xml";
        try {
            File file = new File(fileName);
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(file);

            doc.getDocumentElement().normalize();
            NodeList recordList = doc.getElementsByTagName("record");

            for (int i = 0; i < recordList.getLength(); i++) {
                Element recordElement = (Element) recordList.item(i);
                String name = recordElement.getElementsByTagName("name").item(0).getTextContent();
                String postalZip = recordElement.getElementsByTagName("postalZip").item(0).getTextContent();
                String region = recordElement.getElementsByTagName("region").item(0).getTextContent();
                String country = recordElement.getElementsByTagName("country").item(0).getTextContent();
                String address = recordElement.getElementsByTagName("address").item(0).getTextContent();
                String list = recordElement.getElementsByTagName("list").item(0).getTextContent();

                System.out.println("Name: " + name);
                System.out.println("Postal Zip: " + postalZip);
                System.out.println("Region: " + region);
                System.out.println("Country: " + country);
                System.out.println("Address: " + address);
                System.out.println("List: " + list);
                System.out.println("-----");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
} 

